# Generated by Django 4.1.5 on 2023-01-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredient_name', models.CharField(choices=[('Olive Oil', 'Olive oil'), ('Flour', 'Flour'), ('Butter', 'Butter'), ('Chicken', 'Chicken'), ('Sugar', 'Sugar'), ('Salt', 'Salt'), ('Egg', 'Egg'), ('Rice', 'Rice'), ('Beef', 'Beef'), ('Onion', 'Onion'), ('Lettuce', 'Lettuce'), ('Tomato', 'Tomato'), ('Pickles', 'Pickles'), ('Relish', 'Relish'), ('Cucumber', 'Cucumber'), ('Blueberry', 'Blueberry'), ('Bananas', 'Bananas'), ('Strawberry', 'Strawberry'), ('Kiwi', 'Kiwi'), ('Cheese', 'CE')], max_length=20)),
                ('Ingredient_quantity', models.FloatField(default=0)),
                ('Ingredient_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_choice', models.CharField(choices=[('DC', 'Double_Cheeseburger'), ('SD', 'Salad'), ('TO', 'Taco'), ('BO', 'Burrito'), ('SS', 'SunnySideup Eggs'), ('SC', 'StrawberryKiwi Cheesecake')], max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('SS', 'SuperSized')], default='M', max_length=2)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('ingredient_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_delights.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_delights.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_delights.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='Menu_Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_delights.menuitem'),
        ),
    ]
