# Generated by Django 4.1.5 on 2023-01-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_delights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='Menu_Item',
        ),
    ]
